export default Object.freeze({
  USER_DETAILS: "UserDetails",
  LISTING_EDIT: "ListingEdit",
  LISTINGS: "Listings",
  LOGIN: "Login",
  ADMIN_CONTACT: "AdminContact",
  REGISTER: "Register",
  GROUPFILTERING: "GroupFiltering",
  GROUPSLIST: "GroupsList",
  SCHEDULE: "Schedule",
  SCHEDULE_ADD: "ScheduleAdd",
  ADDRESS: "Address",
  ADDRESS_ADD: "AddressAdd",
  MAPVIEW: "MapView",
  FORGETPASS: "ForgetPassword",
  RESETPASSWORD: 'ResetPassword',
  USER_DELETE: 'UserDeleteScreen',
  GROUPDETAILS: 'GroupDetails',
  SUBSCRIPTIONS: 'Subscriptions',
});
